2025-05-22 16:07:52,007 INFO    MainThread:69109 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_setup.py:_flush():70] Configure stats pid to 69109
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_setup.py:_flush():70] Loading settings from /Users/albertomoreno/.config/wandb/settings
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_setup.py:_flush():70] Loading settings from /Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/wandb/settings
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_init.py:setup_run_log_directory():724] Logging user logs to ./wandb_runs/seed_7/wandb/run-20250522_160752-840l08v4/logs/debug.log
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to ./wandb_runs/seed_7/wandb/run-20250522_160752-840l08v4/logs/debug-internal.log
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_init.py:init():852] calling init triggers
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_init.py:init():857] wandb.init called with sweep_config: {'agent_type': 'epsilon_greedy', 'epsilon': 0.5, 'epsilon_final': 0.05, 'exploration_fraction': 0.9, 'extrinsic_coef': 2, 'hidden_dim': 64, 'predictor_update_freq': 4}
config: {'env_id': 'Acrobot-v1', 'env_name': 'Acrobot-v1', 'exp_name': 'rnd_experiment', 'num_envs': 1, 'total_timesteps': 200000, 'learning_rate': 0.0001, 'gamma': 0.99, 'tau': 1.0, 'buffer_size': 10000, 'batch_size': 16, 'target_network_frequency': 500, 'seed': 7, 'seeds': [42, 1337, 2025, 7, 99], 'capture_video': False, 'agent_type': 'epsilon_greedy', 'wandb_project_name': 'EpistemicUncertaintyRL', 'save_model': False, 'track': True, 'predictor_hidden_dim': 32, 'target_hidden_dim': 32, 'intrinsic_coef': 1.0, 'extrinsic_coef': 2, 'predictor_update_freq': 4, 'epsilon': 0.5, 'epsilon_final': 0.05, 'exploration_fraction': 0.9, 'train_frequency': 10, 'learning_starts': 10000, 'hidden_dim': 64, '_wandb': {}}
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_init.py:init():893] starting backend
2025-05-22 16:07:52,008 INFO    MainThread:69109 [wandb_init.py:init():897] sending inform_init request
2025-05-22 16:07:52,022 INFO    MainThread:69109 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-22 16:07:52,023 INFO    MainThread:69109 [wandb_init.py:init():907] backend started and connected
2025-05-22 16:07:52,024 INFO    MainThread:69109 [wandb_run.py:_config_callback():1436] config_cb None None {'agent_type': 'epsilon_greedy', 'epsilon': 0.5, 'epsilon_final': 0.05, 'exploration_fraction': 0.9, 'extrinsic_coef': 2, 'hidden_dim': 64, 'predictor_update_freq': 4}
2025-05-22 16:07:52,025 INFO    MainThread:69109 [wandb_init.py:init():1005] updated telemetry
2025-05-22 16:07:52,045 INFO    MainThread:69109 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-22 16:07:53,012 INFO    MainThread:69109 [wandb_init.py:init():1104] starting run threads in backend
2025-05-22 16:07:53,117 INFO    MainThread:69109 [wandb_run.py:_console_start():2573] atexit reg
2025-05-22 16:07:53,117 INFO    MainThread:69109 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-22 16:07:53,117 INFO    MainThread:69109 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-22 16:07:53,117 INFO    MainThread:69109 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-22 16:07:53,118 INFO    MainThread:69109 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-22 16:13:13,325 INFO    MainThread:69109 [wandb_run.py:_finish():2321] finishing run a-morenosanchez-tu-delft/EpistemicUncertaintyRL/840l08v4
2025-05-22 16:13:13,326 INFO    MainThread:69109 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 0
2025-05-22 16:13:13,326 INFO    MainThread:69109 [wandb_run.py:_restore():2520] restore
2025-05-22 16:13:13,326 INFO    MainThread:69109 [wandb_run.py:_restore():2526] restore done
2025-05-22 16:14:37,052 WARNING MsgRouterThr:69109 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-22 16:14:37,076 INFO    MsgRouterThr:69109 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 3 handles.
2025-05-22 16:14:37,096 INFO    MainThread:69109 [wandb_run.py:_restore():2520] restore
2025-05-22 16:14:37,096 INFO    MainThread:69109 [wandb_run.py:_restore():2526] restore done
2025-05-22 16:14:37,096 ERROR   MainThread:69109 [wandb_run.py:_atexit_cleanup():2559] Problem finishing run
Traceback (most recent call last):
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2550, in _atexit_cleanup
    self._on_finish()
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2806, in _on_finish
    wait_with_progress(
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
  File "/Users/albertomoreno/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/albertomoreno/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/albertomoreno/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/asyncio_compat.py", line 74, in run
    return asyncio.run(self._run_or_cancel(fn))
  File "/Users/albertomoreno/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/albertomoreno/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/asyncio_compat.py", line 98, in _run_or_cancel
    return fn_task.result()
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 82, in progress_loop_with_timeout
    return await _wait_handles_async(
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 130, in _wait_handles_async
    async with asyncio_compat.open_task_group() as task_group:
  File "/Users/albertomoreno/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/contextlib.py", line 206, in __aexit__
    await anext(self.gen)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/asyncio_compat.py", line 190, in open_task_group
    await task_group._wait_all()
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/lib/asyncio_compat.py", line 159, in _wait_all
    raise exc
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 128, in wait_single
    results[index] = await handle.wait_async(timeout=timeout)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/mailbox/mailbox_handle.py", line 126, in wait_async
    response = await self._handle.wait_async(timeout=timeout)
  File "/Users/albertomoreno/Documents/Universidad/Year3/RP/EpistemicUncertaintyRL/.venv/lib/python3.10/site-packages/wandb/sdk/mailbox/response_handle.py", line 128, in wait_async
    raise HandleAbandonedError()
wandb.sdk.mailbox.mailbox_handle.HandleAbandonedError
